### ISSUE TITLE
Architect AST definition discussion

### ISSUE THREAD

**Issue by kristoferjoseph** [architect/parser#102]
While working with the Architect, on many occasions I have needed to manipulate an existing `app.arc` file.

This is possible with some workarounds using tokens generated from the current state of the parser / lexer, but in order to have lossless editing that can survive a round trip we should define a a proper AST.

@brianleroux asked me to open an issue to arrive at a consensus for this format with @filmaj & @ryanblock 

Feedback is also welcome from the community on insights into ways to build a more robust and accessible AST round trip.

**Comment by brianleroux** [comment]
thx for kicking this discussion off kj; there are a few places to draw inspiration but as mentioned we really just need to figure out consensus on the format we think makes the most sense. the lexer creates an array of tokens. the 'parser' should create an AST and then serialize to the final output… we currently skip to the final json output (which does not include comments) and need this intermediate format to create non-lossy output from mutated arcfiles. 

we will also need to use/encode passes for the other formats we support, JSON, YAML and TOML, which do have various AST implementations:

- json ast 
- yaml ast 
- toml ast  

probably want to keep it as close to the ground we've already covered in the lexer which essentially means structuring things like a tree (or map or object) instead of a stream (or vector or array). think we want to have a very shallow hierarchy still; and need to agree to whatever we want the property name to be that represents child nodes. 

given the following `app.arc`

```arc
# hi comment here
@app 
foo # another here

@http 
get /

@static 
ignore
  foo.txt 

@tables 
data
  scopeID *String
```

we get the following lexeme tokens: 

```json
[{"type":"pragma","value":"app","line":1,"column":1},{"type":"space","value":" ","line":1,"column":5},{"type":"newline","value":"\n","line":1,"column":6},{"type":"string","value":"foo","line":2,"column":1},{"type":"space","value":" ","line":2,"column":4},{"type":"comment","value":"# another here","line":2,"column":5},{"type":"newline","value":"\n","line":2,"column":19},{"type":"newline","value":"\n","line":3,"column":1},{"type":"pragma","value":"http","line":4,"column":1},{"type":"space","value":" ","line":4,"column":6},{"type":"newline","value":"\n","line":4,"column":7},{"type":"string","value":"get","line":5,"column":1},{"type":"space","value":" ","line":5,"column":4},{"type":"string","value":"/","line":5,"column":5},{"type":"newline","value":"\n","line":5,"column":6},{"type":"newline","value":"\n","line":6,"column":1},{"type":"pragma","value":"static","line":7,"column":1},{"type":"space","value":" ","line":7,"column":8},{"type":"newline","value":"\n","line":7,"column":9},{"type":"string","value":"ignore","line":8,"column":1},{"type":"newline","value":"\n","line":8,"column":7},{"type":"space","value":" ","line":9,"column":1},{"type":"space","value":" ","line":9,"column":2},{"type":"string","value":"foo.txt","line":9,"column":3},{"type":"space","value":" ","line":9,"column":10},{"type":"newline","value":"\n","line":9,"column":11},{"type":"newline","value":"\n","line":10,"column":1},{"type":"pragma","value":"tables","line":11,"column":1},{"type":"space","value":" ","line":11,"column":8},{"type":"newline","value":"\n","line":11,"column":9},{"type":"string","value":"data","line":12,"column":1},{"type":"newline","value":"\n","line":12,"column":5},{"type":"space","value":" ","line":13,"column":1},{"type":"space","value":" ","line":13,"column":2},{"type":"string","value":"scopeID","line":13,"column":3},{"type":"space","value":" ","line":13,"column":10},{"type":"string","value":"*String","line":13,"column":11},{"type":"newline","value":"\n","line":13,"column":18}]
```

and we expect the following fully parsed JSON output:
 
```json
{
  "app": ["foo"],
  "http": [["get", "/"]],
  "static": [{"ignore": ["foo.txt"]}],
  "tables": [{"data": {"scopeID": "*String"}}]
}
```

proposal AST format:

```json
{
  "type": "app.arc",
  "children": [
    {"type": "newline", value: "\n"},
    {"type": "comment", value: "hi comment here"},
    {"type": "newline", value: "\n"},
    {"type": "pragma", value: "app", "children": [
      {"type": "string", "value": "foo"},
      {"type": "space", "value": " "},
      {"type": "comment", value: "hi comment here"},
    ] },
   /*  ... you get the idea ... */
  ]
}
```

things we need to add/consider: 

- line numbers 

--- 

anything I'm missing?

**Comment by brianleroux** [comment]
shipping in 5.x!

**Comment by ryanblock** [comment]
Woo, congrats @brianleroux!
